/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barrosfilhos.controle.view;

import barrosfilhos.controle.utils.ArquivoDae;
import barrosfilhos.controle.utils.PDFDAE;
import barrosfilhos.controle.utils.ArquivoDarf;
import barrosfilhos.controle.utils.PDFDARF;
import barrosfilhos.controle.utils.ArquivoFgts;
import barrosfilhos.controle.utils.ArquivoGps;
import barrosfilhos.controle.utils.PDFFGTS;
import barrosfilhos.controle.utils.PDFGPS;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zigui
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VerificarDarfs = new javax.swing.JButton();
        VerificarFgts = new javax.swing.JButton();
        VerificarDae = new javax.swing.JButton();
        VerificarGps = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guias");

        VerificarDarfs.setText("Verificar Darfs");
        VerificarDarfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarDarfsActionPerformed(evt);
            }
        });

        VerificarFgts.setText("Verificar Fgts");
        VerificarFgts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarFgtsActionPerformed(evt);
            }
        });

        VerificarDae.setText("Verificar Dae");
        VerificarDae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarDaeActionPerformed(evt);
            }
        });

        VerificarGps.setText("Verificar Gps");
        VerificarGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarGpsActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo_barros.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VerificarDarfs)
                            .addComponent(VerificarGps))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VerificarDae)
                            .addComponent(VerificarFgts)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {VerificarDae, VerificarDarfs, VerificarFgts});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerificarDarfs)
                    .addComponent(VerificarDae))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerificarFgts)
                    .addComponent(VerificarGps))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {VerificarDae, VerificarDarfs, VerificarFgts});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VerificarDarfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarDarfsActionPerformed
        JOptionPane.showMessageDialog(null,"Realizar Leitura de Darfs");
        ArquivoDarf.createFolder();
        try {
            PDFDARF.LerDarfs();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Darfs Lido com Sucesso!");
        
    }//GEN-LAST:event_VerificarDarfsActionPerformed

    private void VerificarFgtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarFgtsActionPerformed
         JOptionPane.showMessageDialog(null,"Realizar Leitura de FGTS");
        ArquivoFgts.createFolder();
        try {
            PDFFGTS.LerFGTSs();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"FGTS Lido com Sucesso!");
    }//GEN-LAST:event_VerificarFgtsActionPerformed

    private void VerificarDaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarDaeActionPerformed
       
        JOptionPane.showMessageDialog(null,"Realizar Leitura de DAE");
        ArquivoDae.createFolder();
        try {
            PDFDAE.LerDAE();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"DAE Lido com Sucesso!");
    }//GEN-LAST:event_VerificarDaeActionPerformed

    private void VerificarGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarGpsActionPerformed
      JOptionPane.showMessageDialog(null,"Realizar Leitura de GPS");
        ArquivoGps.createFolder();
        try {
            PDFGPS.LerGps();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"GPS Lido com Sucesso!");
    }//GEN-LAST:event_VerificarGpsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerificarDae;
    private javax.swing.JButton VerificarDarfs;
    private javax.swing.JButton VerificarFgts;
    private javax.swing.JButton VerificarGps;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
